### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by prrrnd** [abtion/guidelines#24]
https://opensource.guide/code-of-conduct/

**Comment by heatherm** [comment]
I have created a draft that is under review by the partners: https://abtion.slack.com/archives/C02A0DJMJ/p1568895714006100. @hofmanhansen will you push the draft here once ok'd so we can iterate on it with the org?

**Comment by prrrnd** [comment]
@heatherm @hofmanhansen Any updates on this one?

**Comment by heatherm** [comment]
@hofmanhansen ping :)

**Comment by heatherm** [comment]
Added, closing.
