### ISSUE TITLE
Use 'Co-authored-by' for pairing attribution

### ISSUE THREAD

**Issue by GeoffAbtion** [abtion/guidelines#26]
https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

```
$ git commit -m "Refactor usability tests.
>
>
Co-authored-by: name <name@example.com>
Co-authored-by: another-name <another-name@example.com>"
```

**Comment by GeoffAbtion** [comment]
This should be used instead of the current "git pair" fake email address hack.

@bohme and I are working on a utility similar to the `git pair` script that will automatically add the attributions to the end of commit messages.

**Comment by prrrnd** [comment]
Great idea. Where is the project currently being developed? I'd like to help or do code reviews on it.

**Comment by NorfeldtAbtion** [comment]
just FYI when using vscode share and committing the messages via git in vscode then it adds it.

**Comment by heatherm** [comment]
@GeoffAbtion would love to help.

**Comment by GeoffAbtion** [comment]
This is my current favourite implementation: https://github.com/cac04/git-pair

**Comment by NorfeldtAbtion** [comment]
That looks like a good solution

**Comment by runephilosof-abtion** [comment]
I have been using https://github.com/findmypast-oss/git-mob.
Compared to git pair above, it does not require adding a git hook to insert the text in commit messages (except if you also want it inserted when you use the `-m` argument to Git)

**Comment by MarkusAbtion** [comment]
I use [git-mob](https://github.com/findmypast-oss/git-mob) like @runephilosof-abtion and I find it pretty simple to use:
By running `git mob rp`, I've set Rune to be my pair for upcoming commits.

And:
@prrrnd mentioned [this tool](https://github.com/abtion/gitmessage) recently.

**Comment by hcarreras** [comment]
We are experimenting with [git message](https://github.com/abtion/gitmessage)
