### ISSUE TITLE
Extract muffi-template to own repo

### ISSUE THREAD

**Issue by bohme** [abtion/guidelines#27]
Muffi-template = rails template

**Comment by bohme** [comment]
#10

**Comment by GeoffAbtion** [comment]
The ["muffi_template"](https://github.com/abtion/guidelines/tree/master/rails/muffi_template) in this repository) should probably just be deleted (rather than extracted) since it has been replaced by https://github.com/abtion/muffi

**Comment by bohme** [comment]
closing this because this exists: https://github.com/abtion/muffi
